# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://shunkakinoki.github.io/shun_notebook/"

git_url = "https://github.com/shunkakinoki/shun_notebook/tree/master/"


def custom_doc_links(name):
    return None
